class DataManifest {
  String first =
      "Chúng tôi muốn xây dựng cộng đồng thân thiện và tích cực! Tiêu chuẩn này được đưa ra để hướng dẫn người bán và người mua gìn giữ một thị trường mua bán an toàn. Vui lòng đọc Những việc nên và không nên làm dưới đây khi sử dụng ứng dụng của chúng tôi. Bằng việc dùng ứng dụng này, bạn đồng ý với các Điều khoản sử dụng của chúng tôi. Chúng tôi cam kết nỗ lực gìn giữ sự an toàn cho cộng đồng mua bán này.";
  List<Map<String, String>> second = [
    {'1. Bán hàng thật, không quảng cáo': 'Ứng dụng là ứng dụng hỗ trợ người mua và người bán giao dịch với nhau chứ không phải là nền tảng để quảng cáo. Bạn chỉ nên đăng những sản phẩm mà bạn muốn bán trên ứng dụn. Dưới đây là một số ví dụ về việc vi phạm quy tắc này: - Kết nối trang đăng bán sản phẩm tới một website riêng biệt khác. - Phần mô tả, hình ảnh hoặc tên gọi của sản phẩm chứa thông tin hướng dẫn người mua kết nối với người bán qua một ứng dụng hoặc phương tiện khác. Chúng tôi hiểu rằng người mua và người bán luôn có nhu cầu trao đổi thông tin với nhau, do vậy, tính năng Trả giá đã được tích hợp trong ứng dụng để hỗ trợ tối đa mọi giao dịch của người dùng.'},
    {'2. Làm thế nào để sản phẩm của bạn nổi bật?': 'Sẽ chẳng có người mua nào chú ý nếu ảnh sản phẩm của bạn không hấp dẫn. Hãy chứng tỏ kỹ năng chụp ảnh của bạn và sáng tạo ra những bức ảnh thật đẹp (Xem Mẹo bán hàng trên ứng dụng). Bên cạnh đó, hãy là người bán hàng chân thật, mô tả sản phẩm thật chính xác và chi tiết vì khách hàng luôn muốn biết rõ về sản phẩm mà họ mua. Việc này cũng sẽ giúp bạn nhận được những đánh giá tích cực từ họ!'},
    {'3. Tôn trọng lẫn nhau': 'Chúng tôi muốn xây dựng một cộng đồng an toàn để mọi người cùng tận hưởng niềm vui mua sắm trên di động, vì vậy, hãy đăng tải những nội dung lành mạnh và phù hợp với tất cả mọi người; không sử dụng ngôn ngữ thô tục, đăng các nội dung xấu hay làm phiền người khác. Trong cộng đồng, người dùng phải tôn trọng lẫn nhau và cư xử có thiện chí. Dù bạn mua hay bán hàng trên ứng dụng, hãy tuân thủ những quy tắc dưới đây để đảm bảo mọi người cùng được mua sắm dễ dàng!'},
  ];
   List<Map<String, String>> third = [
    {'1. Mạo danh người khác': 'Mạo danh người khác để lừa đảo dưới bất kỳ hình thức nào bị xem là hành vi vi phạm nghiêm trọng Tiêu chuẩn cộng đồng của ứng dụng. Nếu bạn sử dụng hình ảnh của người khác, vui lòng tôn trọng bản quyền và dẫn nguồn khi cần thiết. Một số ví dụ về hành vi mạo danh: - Sử dụng thông tin cá nhân của người khác (thông tin liên lạc, hình ảnh, v.v...) mà không được sự cho phép của người đó. - Sử dụng danh tính của người khác với mục đích giả mạo và lừa đảo. Hãy chung tay xây dựng cộng đồng lành mạnh! Nếu thấy có người dùng mạo danh bạn hay người khác, vui lòng liên hệ với chúng tôi.'},
    {'2. Đăng bán hàng giả, hàng nhái': 'Chỉ đăng bán các mặt hàng chính hãng trên ứng dụng. Chúng tôi nghiêm cấm việc đăng bán hàng giả, hàng nhái bởi đó là hành vi vi phạm pháp luật. Ứng dụng có quyền báo cáo và xóa các mặt hàng này.'},
    {'3. Đăng bán dịch vụ': 'Chúng tôi không cho phép người dùng đăng bán dịch vụ trên ứng dụng này.'},
    {'4. Xây dựng chính sách hoàn trả không phù hợp': 'Người bán có quyền xây dựng chính sách hoàn trả riêng nếu không mâu thuẫn với chính sách hoàn trả hiện thời của ứng dụng.'},
  ];
  String fourth = "Mọi người dùng đều đóng vai trò quan trọng trong việc gìn giữ sự an toàn cho cộng đồng. Đây là môi trường cởi mở để mọi người cùng mua bán dễ dàng. Hãy tôn trọng lẫn nhau và tạo nên cộng đồng mua bán trên di động tuyệt vời nhất. Nếu phát hiện người dùng vi phạm các quy tắc này, bạn hãy thông báo cho chúng tôi bằng cách Tố cáo người dùng/ sản phẩm. Tuy nhiên, chúng tôi không đảm bảo người dùng hay sản phẩm này sẽ bị xóa và quyền quyết định cuối cùng thuộc về ứng dụng";
  String fifth = "Chúng tôi mong nhận được phản hồi và sẵn sàng tiếp thu mọi ý kiến của bạn. Hãy liên hệ với chúng tôi khi có bất cứ yêu cầu hay đề xuất nào nhằm tạo nên trải nghiệm mua bán trên di động tuyệt vời nhất.";
}
