name: android_project
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  flutter_snake_navigationbar: ^0.6.1
  dots_indicator: ^2.0.0
  path_drawing: ^1.0.1
  shared_preferences: ^2.3.0
  flutter_facebook_auth: ^7.0.0
  google_sign_in: ^6.2.1
  gal: ^2.3.0
  fluentui_system_icons: ^1.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.1
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.1
  image: ^4.2.0
  clean_captcha: ^0.0.2
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  speech_to_text: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/image/
  uses-material-design: true
