server:
  port: 8080
  servlet:
    multipart:
      multipart-enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  address: 192.168.1.9
spring:
  application:
    name: BE_PBL6_FastOrderSystem
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  datasource:
    url: jdbc:mysql://localhost:3306/db_pbl6
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:postgresql://dpg-csest4e8ii6s7398nal0-a.oregon-postgres.render.com:5432/db_pbl6_tz5x
#    username: root
#    password: DsDw5g9IuY1awhrklrRMeEjOteIiGg0V
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
#      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      signerKey: "W31fqJQUxdNSy/Y+F+RFsa/Zi4hx3sX2tfRH/dAk/0342mbKCFpdljSyUkeE59vxGYdSPYIAW2UW+pExDCD+1Q=="
      valid-duration: 86400 # 1 ngày
      refreshable-duration: 86400 # 1 ngày
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope:
              - email
              - profile
            redirect-uri: "${BASE_URL}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: google
          facebook:
            client-id: ${facebook.client.id}
            client-secret: ${facebook.client.secret}
            scope:
              - email
              - public_profile
            redirect-uri: "${BASE_URL}/login/oauth2/code/facebook"
            authorization-grant-type: authorization_code
            client-name: facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          facebook:
            authorization-uri: https://www.facebook.com/v2.8/dialog/oauth
            token-uri: https://graph.facebook.com/v2.8/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,first_name,last_name
            user-name-attribute: id
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.thymeleaf: TRACE
BASE_URL: http://localhost:8080
#BASE_URL: https://pbl6-fastordersystem.onrender.com

