// actionTypes.js
const types = {
  // Category
  FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_ERROR: 'FETCH_CATEGORY_ERROR',

  CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',

  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',

  // Product
  FETCH_PRODUCTS_BEST_SALE_SUCCESS: 'FETCH_PRODUCTS_BEST_SALE_SUCCESS',
  FETCH_PRODUCTS_BY_ID_CATEGORY_SUCCESS: 'FETCH_PRODUCTS_BY_ID_CATEGORY_SUCCESS',
  FETCH_PRODUCT_BY_ID_SUCCESS: 'FETCH_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCTS_BY_ID_STORE_SUCCESS: 'FETCH_PRODUCTS_BY_ID_STORE_SUCCESS',

  // store
  FETCH_STORE_SUCCESS: 'FETCH_STORE_SUCCESS',
  FETCH_STORE_BY_ID_SUCCESS: 'FETCH_STORE_BY_ID_SUCCESS',

};

export default types;
