// actionTypes.js
const types = {
  // Category
  FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_ERROR: 'FETCH_CATEGORY_ERROR',

  CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',

  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',

  // Product
  FETCH_PRODUCTS_BEST_SALE_SUCCESS: 'FETCH_PRODUCTS_BEST_SALE_SUCCESS',
  FETCH_PRODUCTS_BY_ID_CATEGORY_SUCCESS: 'FETCH_PRODUCTS_BY_ID_CATEGORY_SUCCESS',
  FETCH_PRODUCT_BY_ID_SUCCESS: 'FETCH_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCTS_BY_ID_STORE_SUCCESS: 'FETCH_PRODUCTS_BY_ID_STORE_SUCCESS',

  // store
  FETCH_STORE_SUCCESS: 'FETCH_STORE_SUCCESS',
  FETCH_STORE_BY_ID_SUCCESS: 'FETCH_STORE_BY_ID_SUCCESS',

  // authentication => Register New User
  REGISTER_NEW_USER_SUCCESS: 'REGISTER_NEW_USER_SUCCESS',
  REGISTER_NEW_USER_ERROR: 'REGISTER_NEW_USER_ERROR',
  // authentication => Login User
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  // auth => update profile
  AUTH_UPDATE_ACCOUNT: 'AUTH_UPDATE_ACCOUNT',

  // user
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',

  // size
  FETCH_SIZE_SUCCESS: 'FETCH_SIZE_SUCCESS',

};

export default types;
